import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
          <nav>
            <img src="" alt="Logo" />
            <a href="#Event">Home</a>
            <a href="#Event">Events</a>
            <a href="#Event">About Us</a>
          </nav>
      </header>
      <main className={styles.main}>


      </main>
      <footer className={styles.footer}>

      </footer>
    </>
  )
}
