import Head from 'next/head'
import Image from 'next/image'
import Link  from 'next/link';
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Blog Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
          <nav>
            <img src="" alt="Logo" />
            <Link href="/" passHref>Home</Link>
            <Link href="/events" passHref>Events</Link>
            <Link href="/about-us" passHref>About Us</Link>
          </nav>
      </header>
      <main className={styles.main}>
      <h1>Events pages</h1>

      {data.map(ev => <Link key={ev.id} href={`/events/${ev.id}`} passHref><Image width={200} height={'100%'} alt={ev.title} src={data.image} /><h2>{ev.title}</h2><p>{ev.description}</p></Link> )}


      </main>
      <footer className={styles.footer}>
        <p>Blog 2023 Всі права захищені</p>
      </footer>
    </>
  )
}





export async function getServerSideProps(){
  const {events_categories} = await import('/data/data.json');
  console.log(events_categories)

  return {
    props:{
      data: events_categories,
    }
  }
}